export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";
export const FETCH_FAILED = "FETCH_FAILED";
export const ORDER_DETAILS = 'ORDER_DETAILS';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILURE = 'PURCHASE_FAILURE';
export const PURCHASE_START = 'PURCHASE_START';
